name: sunfoxx_landing
description: My personal landing

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.4
  simple_animations: 1.3.6
  animated_text_kit: 2.0.0
  dio: ^3.0.8
  firebase_core: 0.4.4
  auto_size_text: 2.1.0
  build_runner: ^1.7.4
  flutter_widgets: ^0.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-LightItalic.ttf